import { NextResponse } from "next/server";
import connectDB from "@/lib/mongodb";
import Blog from "@/models/Blog"; // Your Mongoose Blog model
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth"; // Your NextAuth configuration

/**
 * @method GET
 * @route /api/blogs
 * @description Fetches all blog posts from the database.
 * @returns {NextResponse} JSON response containing all blogs or an error.
 */
export async function GET() {
  try {
    // Establish database connection
    await connectDB();
    console.log("Connected to DB for GET /api/blogs");

    // Fetch all blogs, sort by creation date (newest first), and exclude the Mongoose version key
    const blogs = await Blog.find({}).sort({ createdAt: -1 }).select("-__v");

    // Return the fetched blogs as a JSON response
    return NextResponse.json(blogs, { status: 200 });
  } catch (error) {
    // Log the error for server-side debugging
    console.error("Error fetching blogs (GET /api/blogs):", error);
    // Return an error response to the client
    return NextResponse.json(
      { error: "Error fetching blogs", details: error.message },
      { status: 500 }
    );
  }
}

/**
 * @method POST
 * @route /api/blogs
 * @description Creates a new blog post. Requires admin authentication.
 * Slug and lowercase title are automatically generated by the Mongoose schema's pre-save hooks.
 * @param {Request} request - The incoming Next.js request object.
 * @returns {NextResponse} JSON response with the created blog or an error.
 */
export async function POST(request) {
  try {
    // 1. Authentication Check: Ensure only authorized admins can create blogs
    const session = await getServerSession(authOptions);
    // Hardcoded admin email check - consider a more robust role-based system for production
    if (!session || session.user.email !== "admin@email.com") {
      console.warn(
        "Unauthorized attempt to POST /api/blogs:",
        session?.user?.email || "No session"
      );
      return NextResponse.json(
        { error: "Unauthorized. Admin access required." },
        { status: 403 }
      );
    }

    // 2. Parse Request Body
    const body = await request.json();
    console.log("Received request body for POST /api/blogs:", body);

    // 3. Validate Required Fields in the Request Body
    // These fields must be present in the incoming JSON payload
    const requiredFields = ["title", "content", "banner", "author"];
    const missingFields = requiredFields.filter((field) => !body[field]);

    if (missingFields.length > 0) {
      console.log("Missing required fields for blog creation:", missingFields);
      return NextResponse.json(
        {
          error: "Missing required fields",
          details: `The following fields are required: ${missingFields.join(
            ", "
          )}`,
        },
        { status: 400 } // Bad Request
      );
    }

    // 4. Validate Author Object Structure
    // The author must have 'id', 'name', and 'email' properties
    if (
      !body.author ||
      !body.author.id ||
      !body.author.name ||
      !body.author.email
    ) {
      console.log("Invalid author information provided.");
      return NextResponse.json(
        {
          error: "Invalid author information",
          details: "Author must include id, name, and email",
        },
        { status: 400 } // Bad Request
      );
    }

    // 5. Establish Database Connection (if not already connected)
    try {
      await connectDB();
      console.log("Successfully connected to database for POST /api/blogs");
    } catch (dbError) {
      console.error(
        "Database connection error during POST /api/blogs:",
        dbError
      );
      return NextResponse.json(
        { error: "Database connection failed", details: dbError.message },
        { status: 500 }
      );
    }

    // The Mongoose schema's `pre('validate')` hook will generate the slug
    // and `lowercase` title from `body.title` automatically before saving.

    // 6. Create the Blog Post
    try {
      const blog = await Blog.create({
        title: body.title.trim(), // Trim whitespace from title
        content: body.content, // Editor.js content is an object, passed directly
        banner: body.banner,
        location: body.location || "Unknown", // Use provided location or default
        author: {
          // Ensure author object matches schema
          id: body.author.id,
          name: body.author.name,
          email: body.author.email,
        },
        // 'slug' and 'lowercase' fields are handled by the Mongoose schema's pre-validate hook
      });

      console.log("Successfully created blog:", blog._id);
      return NextResponse.json(blog, { status: 201 }); // 201 Created
    } catch (createError) {
      console.error("Error creating blog (POST /api/blogs):", createError);

      // Handle specific Mongoose errors
      if (createError.name === "ValidationError") {
        // Mongoose schema validation errors
        const validationErrors = Object.values(createError.errors).map(
          (err) => err.message
        );
        console.log("Mongoose Validation errors:", validationErrors);
        return NextResponse.json(
          {
            error: "Validation error",
            details: validationErrors,
          },
          { status: 400 }
        );
      }

      // Handle MongoDB duplicate key error (code 11000)
      // This is particularly important for the `slug` field with `unique: true`
      if (createError.code === 11000) {
        console.log(
          "Duplicate key error (slug or title unique index):",
          createError.keyValue
        );
        return NextResponse.json(
          { error: "A blog with this title or slug already exists." },
          { status: 409 } // Conflict
        );
      }

      // Catch any other unexpected errors during creation
      return NextResponse.json(
        {
          error: "Error creating blog",
          details: createError.message,
        },
        { status: 500 } // Internal Server Error
      );
    }
  } catch (error) {
    // Catch any errors that occur before the main try-catch blocks
    console.error(
      "Unexpected top-level error in POST /api/blogs handler:",
      error
    );
    return NextResponse.json(
      {
        error: "An unexpected error occurred",
        details: error.message,
      },
      { status: 500 }
    );
  }
}
